<a href="https://colab.research.google.com/github/239y1a3931-sudo/Agentic-AI/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd

series

In [ ]:
#using List
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#changing index
s=pd.Series([1,2,3,4,5] ,index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
stu    "name":"nicky","age":21
}
se=pd.Series(stu)
print(se)

name    nicky
age        21
dtype: object

In [ ]:
a=pd.Series([1,4,6,8,9])

In [ ]:
a+3
a-5

0   -4
1   -1
2    1
3    3
4    4
dtype: int64

In [ ]:
a.mean()

np.float64(5.6)

In [ ]:
a.max()
a.min()
a.sum()
a.describe()

count    5.000000
mean     5.600000
std      3.209361
min      1.000000
25%      4.000000
50%      6.000000
75%      8.000000
max      9.000000
dtype: float64

In [ ]:
a[a>5]

2    6
3    8
4    9
dtype: int64

In [ ]:
names=pd.Series(["Nicky","Micky"])
names.str.startswith('N')

0     True
1    False
dtype: bool

In [ ]:
data={
    "name":["Nicky","Vicky"],
    "age":[21,23]
}
dat=[
    {"name":"Nicky","age":21},
    {"name":"Vicky","age":23}
]


d=pd.DataFrame(dat)
print(d)

    name  age
0  Nicky   21
1  Vicky   23

In [ ]:

arr=np.random.rand(3,4)
c=pd.DataFrame(arr,columns=['a','b','c','d'],index=['x','y','z'])
print(c)

          a         b         c         d
x  0.015638  0.742182  0.028222  0.032775
y  0.515585  0.985518  0.025403  0.774154
z  0.708793  0.421872  0.305649  0.503260

In [ ]:
#creating student data
data={
    'name':['nicky','micky','vicky','licky'],
    'age':[21,23,23,25],
    'score':[90,80,77,60],
    'grad':['A','B','c','d']
}
df=pd.DataFrame(data)

In [ ]:
df.index
df.nunique()
df.dtypes

name     object
age       int64
score     int64
grad     object
dtype: object

In [ ]:
df['name']
df.name

0    nicky
1    micky
2    vicky
3    licky
Name: name, dtype: object

In [ ]:
df[['name','age']]

    name  age
0  nicky   21
1  micky   23
2  vicky   23
3  licky   25

In [ ]:
df.loc[0]

name     nicky
age         21
score       90
grad         A
Name: 0, dtype: object

In [ ]:
df.loc[0:2]

    name  age  score grad
0  nicky   21     90    A
1  micky   23     80    B
2  vicky   23     77    c

In [ ]:
df.loc[0:1,'name':'age']

    name  age
0  nicky   21
1  micky   23

In [ ]:
df.iloc[0]

name     nicky
age         21
score       90
grad         A
Name: 0, dtype: object

In [ ]:
df.iloc[0:2]

    name  age  score grad
0  nicky   21     90    A
1  micky   23     80    B

In [ ]:
df.iloc[0:2 ,0:2]

    name  age
0  nicky   21
1  micky   23

In [ ]:
df.iloc[-1]

name     licky
age         25
score       60
grad         d
Name: 3, dtype: object

In [ ]:
df.loc[0,'name']
df.iloc[0,0]

'nicky'

In [ ]:
df[(df['age']>2) & (df['score']>8)]

    name  age  score grad
0  nicky   21     90    A
1  micky   23     80    B
2  vicky   23     77    c
3  licky   25     60    d

In [ ]:
df[(df['age']>2) |(df['score']>8)]

    name  age  score   grad  maths even or odd p or f
0  nicky   21     30  False     99         odd   pass
1  micky   23     30  False     80        even   pass
2  vicky   23     30  False     88        even   pass
3  licky   25     30  False     77         odd   pass

In [ ]:
df.query('score>80 and age>20')

    name  age  score grad
0  nicky   21     90    A

In [ ]:
df.query('grad =="c"')

    name  age  score grad
2  vicky   23     77    c

In [ ]:
df[df['name'].isin(['nicky','vicky'])]

    name  age  score grad
0  nicky   21     90    A
2  vicky   23     77    c

In [ ]:
df['maths']=[99,80,88,77]
print(df)

    name  age  score   grad  maths
0  nicky   21     90   True     99
1  micky   23     80   True     80
2  vicky   23     77  False     88
3  licky   25     60  False     77

In [ ]:
df['grad']=df['score']>=80
print(df)

    name  age  score   grad
0  nicky   21     90   True
1  micky   23     80   True
2  vicky   23     77  False
3  licky   25     60  False

In [ ]:
df['score']=df['score']
print(df)

    name  age  score   grad
0  nicky   21     90   True
1  micky   23     80   True
2  vicky   23     77  False
3  licky   25     60  False

In [ ]:
def evenOdd(maths):
  if maths%2==0:
    return 'even'
  else:
    return 'odd'

In [ ]:
df['even or odd']=df['maths'].apply(evenOdd)
print(df)

    name  age  score   grad  maths even or odd
0  nicky   21     90   True     99         odd
1  micky   23     80   True     80        even
2  vicky   23     77  False     88        even
3  licky   25     60  False     77         odd

In [ ]:
result={
    True:'pass',
    False:"fail"
}
df['p or f']=df['grad'].map(result)
print(df)

    name  age  score   grad  maths even or odd p or f
0  nicky   21     90   True     99         odd   pass
1  micky   23     80   True     80        even   pass
2  vicky   23     77  False     88        even   fail
3  licky   25     60  False     77         odd   fail

In [ ]:
df.dropna()
df.dropna(axis=1)
df.drop(thresh=3)

In [ ]:
df.drop('even or odd',axis=1,inplace=True)
print(df)

    name  age  score   grad  maths p or f
0  nicky   21     90   True     99   pass
1  micky   23     80   True     80   pass
2  vicky   23     77  False     88   fail
3  licky   25     60  False     77   fail

In [ ]:
df.rename(columns={'name':'student'},inplace=True)
print(df)

  student  age  score   grad  maths p or f
0   nicky   21     90   True     99   pass
1   micky   23     80   True     80   pass
2   vicky   23     77  False     88   fail
3   licky   25     60  False     77   fail

In [ ]:
df.replace("fail",np.nan,inplace=True)
print(df)

  student  age  score   grad  maths p or f
0   nicky   21     90   True     99   pass
1   micky   23     80   True     80   pass
2   vicky   23     77  False     88    NaN
3   licky   25     60  False     77    NaN

In [ ]:
df.sort_values(['score'], ascending=True, inplace=True)
print(df)
#single value sorting

  student  age  score   grad  maths p or f
3   licky   25     60  False     77    NaN
2   vicky   23     77  False     88    NaN
1   micky   23     80   True     80   pass
0   nicky   21     90   True     99   pass

In [ ]:
df.sort_values(['age','maths'],ascending=[False,True])
print(df)
#sorting multiple values it will not sort only single value sort will be appear

  student  age  score   grad  maths p or f
3   licky   25     60  False     77    NaN
2   vicky   23     77  False     88    NaN
1   micky   23     80   True     80   pass
0   nicky   21     90   True     99   pass

In [ ]:
d.nsmallest(2,'age')

    name  age even or odd
0  Nicky   21         odd
1  Vicky   23        even

In [ ]:
employees = pd.DataFrame({
    'emp_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'dept_id': [10, 20, 10, 30]
})

departments = pd.DataFrame({
    'dept_id': [10, 20],
    'dept_name': ['Engineering', 'HR']
})